P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F

N_NODES = 5
THRESHOLD = 3
F_NODES = 1

IAT_TTL_SECONDS = 60
CHALLENGE_TTL_SECONDS = 30

PQC_SIG_ALG = "ML-DSA-65"
PQC_KEM_ALG = "ML-KEM-768"
